### model
model_name_or_path: /home/user_liang/materials/LlamaFactory/test/home/user_liang/materials/LlamaFactory/model-llama3.1-8b  # 确保这里是 Qwen3-8B 的权重路径
trust_remote_code: true
flash_attn: fa2

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 64
lora_alpha: 128
lora_target: all
lora_dropout: 0.05
# 注意：System Prompt 可以保留，但对于 Thinking 模型，Prompt 通常更简洁，依靠 <think> 引导
default_system: "You are a senior metallurgist. Answer the question after a comprehensive reasoning process."

### dataset
dataset: my_materials_cot_balanced
template: deepseekr1         # <--- 核心修改：使用 qwen3 模板（如果报错请尝试 deepseek 或 qwen）
cutoff_len: 4096
packing: false
val_size: 0.05
preprocessing_num_workers: 4 # 稍微调大一点加快处理

### training
output_dir: saves/Llama3.1-8B-Materials-LoRA
logging_steps: 1
save_strategy: epoch
save_total_limit: 15
plot_loss: true
overwrite_output_dir: false  # 允许自动发现并继续已有 checkpoint
per_device_train_batch_size: 16
gradient_accumulation_steps: 2
learning_rate: 2.0e-4
num_train_epochs: 15.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000

### eval
eval_strategy: epoch

### extra
report_to: wandb